kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-bamboo-agent-di-mvn-cache
  namespace: atlassian
  labels:
    app: bamboo
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 750Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: atlassian
    name: pvc-bamboo-agent-di-mvn-cache
  hostPath:
    path: "/data/mvn-docker-cache"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-bamboo-agent-di-mvn-cache
  namespace: atlassian
  labels:
    app: bamboo
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 750Gi
